-- Denial Trends Crosswalk DDL & Seed Script
CREATE TABLE IF NOT EXISTS denial_trends_crosswalk (
    remittance_code VARCHAR(255) PRIMARY KEY,
    remittance_description TEXT,
    "group" VARCHAR(255),
    rcm_section VARCHAR(255)
);

-- Seed Data (277 Remittance Code Mappings)
INSERT INTO denial_trends_crosswalk (remittance_code, remittance_description, "group", rcm_section) VALUES
('CO-210, CO-45', 'Payment adjusted because pre-certification/authorization not received timely + Charge exceeds fee schedule/maximum allowable', 'Authorization', 'Front End'),
('PR-207', 'Medical provider not authorized/certified', 'Authorization', 'Front End'),
('15', 'The authorization number is missing, invalid, or does not apply to the billed services or provider.', 'Authorization', 'Front End'),
('39', 'Services denied at the time authorization/pre-certification was requested.', 'Authorization', 'Front End'),
('197', 'Precertification/authorization/notification/pre-treatment absent.', 'Authorization', 'Front End'),
('198', 'Precertification/notification/authorization/pre-treatment exceeded.', 'Authorization', 'Front End'),
('210', 'Payment adjusted because pre-certification/authorization not received in a timely fashion.', 'Authorization', 'Front End'),
('284', 'Precertification/authorization/notification/pre-treatment number may be valid but does not apply to the billed services.', 'Authorization', 'Front End'),
('296', 'Precertification/authorization/notification/pre-treatment number may be valid but does not apply to the provider.', 'Authorization', 'Front End'),
('D80', 'Submitted charges do not reflect the treatment authorized to this provider. Under our guidelines, the claim is denied. Member is responsible for only copays and or co-insurance. Provider may not balance bill member.', 'Authorization', 'Front End'),
('M62', 'Missing/incomplete/invalid treatment authorization code.', 'Authorization', 'Front End'),
('N188', 'The approved level of care does not match the procedure code submitted.', 'Authorization', 'Front End'),
('N35', 'Program integrity/utilization review decision.', 'Authorization', 'Front End'),
('N351', 'Service date outside of the approved treatment plan service dates.', 'Authorization', 'Front End'),
('N385', 'Notification of admission was not timely according to published plan procedures.', 'Authorization', 'Front End'),
('N435', 'Exceeds number/frequency approved /allowed within time period without support documentation.', 'Authorization', 'Front End'),
('N54', 'Claim information is inconsistent with pre-certified/authorized services.', 'Authorization', 'Front End'),
('N630', 'Referral not authorized by attending physician.', 'Authorization', 'Front End'),
('N758', 'Adjusted based on the prior authorization decision.', 'Authorization', 'Front End'),
('PR-197', 'Precertification/authorization absent', 'Authorization', 'Front End'),
('PR-243', 'Services not authorized by network/primary care providers', 'Authorization', 'Front End'),
('CO-197', 'Precertification/authorization absent', 'Authorization', 'Front End'),
('PI-135', 'Claim denied. Preauthorization required.', 'Authorization', 'Front End'),
('135', 'Claim denied. Preauthorization required.', 'Authorization', 'Front End'),
('243', 'Services not authorized by network/primary care providers', 'Authorization', 'Front End'),
('PI-197', 'Precertification/authorization absent', 'Authorization', 'Front End'),
('PR-198', 'Precertification/authorization exceeded', 'Authorization', 'Front End'),
('CO-198', 'Precertification/authorization exceeded', 'Authorization', 'Front End'),
('97', 'Payment adjusted because the benefit for this service is included in the payment/allowance for another service/procedure that has already been adjudicated', 'Bundling / Inclusive', 'Middle'),
('234', 'This procedure is not paid separately.', 'Bundling / Inclusive', 'Middle'),
('M15', 'Separately billed services/tests have been bundled as they are considered components of the same procedure.', 'Bundling / Inclusive', 'Middle'),
('M2', 'Not paid separately when the patient is an inpatient.', 'Bundling / Inclusive', 'Middle'),
('N20', 'Service not payable with other service rendered on the same date.', 'Bundling / Inclusive', 'Middle'),
('PI-16', 'Claim/service lacks information or has submission/billing error(s).', 'Coding', 'Middle'),
('OA-18', 'Duplicate claim/service', 'Duplicate', 'Middle'),
('PI-216', 'Based on NCCI/MUE edits', 'Coding', 'Middle'),
('PI-129', 'Prior processing information appears incorrect', 'Coding', 'Middle'),
('CO-129', 'Prior processing information appears incorrect', 'Coding', 'Middle'),
('PR-216', 'Based on NCCI/MUE edits', 'Coding', 'Middle'),
('PI-246', 'This non-payable code is for required reporting only', 'Coding', 'Middle'),
('PR-16', 'Claim/service lacks information or has submission/billing error(s).', 'Coding', 'Middle'),
('PI-282', 'Service not covered when performed by this provider type', 'Coding', 'Middle'),
('CO-97', 'Included in payment for another service', 'Duplicate', 'Middle'),
('PI-18', 'Duplicate claim/service', 'Duplicate', 'Middle'),
('OA-16', 'Claim/service lacks information or has submission/billing error(s).', 'Coding', 'Middle'),
('129', 'Prior processing information appears incorrect', 'Coding', 'Middle'),
('OA-18, OA-18', 'Duplicate claim/service + Duplicate claim/service', 'Duplicate', 'Middle'),
('PI-11', 'Diagnosis inconsistent with procedure', 'Coding', 'Middle'),
('PR-234', 'This procedure is not paid separately', 'Coding', 'Middle'),
('PR-129', 'Prior processing information appears incorrect', 'Coding', 'Middle'),
('OA-18, CO-45', 'Duplicate claim/service + Charge exceeds fee schedule/maximum allowable', 'Duplicate', 'Middle'),
('PR-97', 'Included in payment for another service', 'Coding', 'Middle'),
('4', 'The procedure code is inconsistent with the modifier used.', 'Coding', 'Middle'),
('5', 'The procedure code/type of bill is inconsistent with the place of service.', 'Coding', 'Middle'),
('8', 'The procedure code is inconsistent with the provider type/specialty (taxonomy).', 'Coding', 'Middle'),
('11', 'The diagnosis is inconsistent with the procedure.', 'Coding', 'Middle'),
('12', 'The diagnosis is inconsistent with the provider type.', 'Coding', 'Middle'),
('16', 'Claim/service lacks information or has submission/billing error(s) which is needed for adjudication.', 'Coding', 'Middle'),
('58', 'Payment adjusted because treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service.', 'Coding', 'Middle'),
('207', 'National Provider identifier - Invalid format.', 'Coding', 'Middle'),
('282', 'The procedure/revenue code is inconsistent with the type of bill.', 'Coding', 'Middle'),
('DAJ', 'Based on the from date and the through date billed, Room and Board was billed for the date of discharge. Room and Board billed charges on the discharge date are not covered under the plan. Therefore the claim is denied.', 'Coding', 'Middle'),
('DUD', 'The bill type is inconsistent with the services and/or admission date and/or discharge status billed. Under our guidelines, the claim is denied.', 'Coding', 'Middle'),
('M20', 'Missing/incomplete/invalid HCPCS.', 'Coding', 'Middle'),
('M50', 'Missing/incomplete/invalid revenue code(s).', 'Coding', 'Middle'),
('M51', 'Missing/incomplete/invalid procedure code(s).', 'Coding', 'Middle'),
('M53', 'Missing/incomplete/invalid days or units of service.', 'Coding', 'Middle'),
('M64', 'Missing/incomplete/invalid other diagnosis.', 'Coding', 'Middle'),
('M67', 'Missing/incomplete/invalid other procedure code(s).', 'Coding', 'Middle'),
('M76', 'Missing/incomplete/invalid diagnosis or condition.', 'Coding', 'Middle'),
('M77', 'Missing/incomplete/invalid/inappropriate place of service.', 'Coding', 'Middle'),
('MA30', 'Missing/incomplete/invalid type of bill.', 'Coding', 'Middle'),
('MA31', 'Missing/incomplete/invalid beginning and ending dates of the period billed.', 'Coding', 'Middle'),
('MA40', 'Missing/incomplete/invalid admission date.', 'Coding', 'Middle'),
('MA42', 'Missing/incomplete/invalid admission source.', 'Coding', 'Middle'),
('MA63', 'Missing/incomplete/invalid principal diagnosis.', 'Coding', 'Middle'),
('MA65', 'Missing/incomplete/invalid admitting diagnosis.', 'Coding', 'Middle'),
('N152', 'Missing/incomplete/invalid replacement claim information.', 'Coding', 'Middle'),
('N208', 'Missing/incomplete/invalid DRG code.', 'Coding', 'Middle'),
('N209', 'Missing/incomplete/invalid taxpayer identification number (TIN).', 'Coding', 'Middle'),
('N265', 'Missing/incomplete/invalid ordering provider primary identifier.', 'Coding', 'Middle'),
('N266', 'Missing/incomplete/invalid ordering provider address.', 'Coding', 'Middle'),
('N286', 'Missing/incomplete/invalid referring provider primary identifier.', 'Coding', 'Middle'),
('N289', 'Missing/incomplete/invalid rendering provider name.', 'Coding', 'Middle'),
('N290', 'Missing/incomplete/invalid rendering provider primary identifier.', 'Coding', 'Middle'),
('N293', 'Missing/incomplete/invalid service facility primary identifier.', 'Coding', 'Middle'),
('N301', 'Missing/incomplete/invalid procedure date(s).', 'Coding', 'Middle'),
('N305', 'Missing/incomplete/invalid injury/accident date.', 'Coding', 'Middle'),
('N318', 'Missing/incomplete/invalid discharge or end of care date.', 'Coding', 'Middle'),
('N34', 'Incorrect claim form/format for this service.', 'Coding', 'Middle'),
('N428', 'Not covered when performed in this place of service.', 'Coding', 'Middle'),
('N56', 'Procedure code billed is not correct/valid for the services billed or the date of service billed.', 'Coding', 'Middle'),
('N569', 'Not covered when performed for the reported diagnosis.', 'Coding', 'Middle'),
('N657', 'This should be billed with the appropriate code for these services.', 'Coding', 'Middle'),
('N77', 'Missing/incomplete/invalid designated provider number.', 'Coding', 'Middle'),
('N798', 'Submit a void request for the original claim and resubmit a new claim.', 'Coding', 'Middle'),
('N799', 'Submitted identifier must be an individual identifier, not group identifier.', 'Coding', 'Middle'),
('CO-16', 'Claim/service lacks information or has submission/billing error(s).', 'Coding', 'Middle'),
('22', 'Payment adjusted because this care may be covered by another payer per coordination of benefits.', 'Coordination of Benefits', 'Front End'),
('MA04', 'Secondary payment cannot be considered without the identity of or payment information from the primary payer.', 'Coordination of Benefits', 'Front End'),
('MA83', 'Did not indicate whether we are the primary or secondary payer.', 'Coordination of Benefits', 'Front End'),
('MA92', 'Missing plan information for other insurance.', 'Coordination of Benefits', 'Front End'),
('N193', 'Alert: Specific federal/state/local program may cover this service through another payer.', 'Coordination of Benefits', 'Front End'),
('N4', 'Missing/Incomplete/Invalid prior Insurance Carrier(s) EOB.', 'Coordination of Benefits', 'Front End'),
('N479', 'Missing Explanation of Benefits (Coordination of Benefits or Medicare Secondary Payer).', 'Coordination of Benefits', 'Front End'),
('PR-109', 'Claim not covered by this payer/contractor', 'Coordination of Benefits', 'Front End'),
('PR-119', 'Benefit maximum reached', 'Coverage / Benefits', 'Front End'),
('PR-187, PR-204, OA-23', 'Consumer spending account payment adjustment + Service/equipment/drug not covered under patient''s current benefit plan + Impact of prior payer adjudication including payments/adjustments.', 'Coverage / Benefits', 'Front End'),
('PR-B22', 'Patient not eligible for this service', 'Coverage / Benefits', 'Front End'),
('OA-23, CO-45', 'Impact of prior payer adjudication including payments/adjustments. + Charge exceeds fee schedule/maximum allowable', 'Coverage / Benefits', 'Front End'),
('PR-242, CO-B13', 'Services not provided by network/primary care providers + Previously paid', 'Coverage / Benefits', 'Front End'),
('PR-279', 'Claim/service denied because of hospice-related responsibility', 'Coverage / Benefits', 'Front End'),
('CO-112', 'Service not furnished directly to patient', 'Coverage / Benefits', 'Front End'),
('CO-45, PR-96', 'Charge exceeds fee schedule/maximum allowable + Non-covered charge(s)', 'Coverage / Benefits', 'Front End'),
('PR-204, OA-23', 'Service/equipment/drug not covered under patient''s current benefit plan + Impact of prior payer adjudication including payments/adjustments.', 'Coverage / Benefits', 'Front End'),
('31', 'Claim denied as patient cannot be identified as our insured.', 'Coverage / Benefits', 'Front End'),
('32', 'Our records indicate the patient is not an eligible dependent.', 'Coverage / Benefits', 'Front End'),
('33', 'Insured has no dependent coverage.', 'Coverage / Benefits', 'Front End'),
('50', 'These are non-covered services because this is not deemed a `medical necessity'' by the payer.', 'Coverage / Benefits', 'Front End'),
('78', 'Non-Covered days/Room charge adjustment.', 'Coverage / Benefits', 'Front End'),
('96', 'Non-covered charge(s).', 'Coverage / Benefits', 'Front End'),
('109', 'Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor.', 'Coverage / Benefits', 'Front End'),
('119', 'Benefit maximum for this time period or occurrence has been reached.', 'Coverage / Benefits', 'Front End'),
('140', 'Patient/Insured health identification number and name do not match.', 'Coverage / Benefits', 'Front End'),
('167', 'This (these) diagnosis(es) is (are) not covered.', 'Coverage / Benefits', 'Front End'),
('177', 'Payment denied because the patient has not met the required eligibility requirements', 'Coverage / Benefits', 'Front End'),
('204', 'This service/equipment/drug is not covered under the patient''s current benefit plan.', 'Coverage / Benefits', 'Front End'),
('272', 'Coverage/program guidelines were not met.', 'Coverage / Benefits', 'Front End'),
('273', 'Coverage/program guidelines were exceeded.', 'Coverage / Benefits', 'Front End'),
('N130', 'Consult plan benefit documents/guidelines for information about restrictions for this service.', 'Coverage / Benefits', 'Front End'),
('N161', 'This drug/service/supply is covered only when the associated service is covered.', 'Coverage / Benefits', 'Front End'),
('N216', 'We do not offer coverage for this type of service or the patient is not enrolled in this portion of our benefit package.', 'Coverage / Benefits', 'Front End'),
('N245', 'Incomplete/invalid plan information for other insurance.', 'Coverage / Benefits', 'Front End'),
('N30', 'Patient ineligible for this service.', 'Coverage / Benefits', 'Front End'),
('N356', 'Not covered when performed with, or subsequent to, a non-covered service.', 'Coverage / Benefits', 'Front End'),
('N375', 'Missing/incomplete/invalid questionnaire/information required to determine dependent eligibility.', 'Coverage / Benefits', 'Front End'),
('N397', 'Benefits are not available for incomplete service(s)/undelivered item(s).', 'Coverage / Benefits', 'Front End'),
('N431', 'Not covered with this procedure.', 'Coverage / Benefits', 'Front End'),
('N525', 'These services are not covered when performed within the global period of another service.', 'Coverage / Benefits', 'Front End'),
('N557', 'This claim/service is not payable under our service area.', 'Coverage / Benefits', 'Front End'),
('N587', 'Policy benefits have been exhausted.', 'Coverage / Benefits', 'Front End'),
('N598', 'Health care policy coverage is primary.', 'Coverage / Benefits', 'Front End'),
('N617', 'This enrollee is in the second or third month of the advance premium tax credit grace period.', 'Coverage / Benefits', 'Front End'),
('N623', 'Not covered when deemed unscientific/unproven/outmoded/experimental/excessive/inappropriate.', 'Coverage / Benefits', 'Front End'),
('PR-26', 'Expenses incurred prior to coverage', 'Coverage / Benefits', 'Front End'),
('PR-200', 'Expenses incurred during lapse in coverage', 'Coverage / Benefits', 'Front End'),
('PR-204', 'Service/equipment/drug not covered under patient''s current benefit plan', 'Coverage / Benefits', 'Front End'),
('PR-33', 'Insured has no dependent coverage', 'Coverage / Benefits', 'Front End'),
('PI-109', 'Claim not covered by this payer/contractor', 'Coordination of Benefits', 'Front End'),
('PR-96', 'Non-covered charge(s)', 'Coverage / Benefits', 'Front End'),
('PR-242', 'Services not provided by network/primary care providers', 'Coverage / Benefits', 'Front End'),
('CO-96', 'Non-covered charge(s)', 'Coverage / Benefits', 'Front End'),
('PI-B20', 'Procedure/service not covered', 'Coverage / Benefits', 'Front End'),
('OA-23', 'Impact of prior payer adjudication including payments/adjustments.', 'Coverage / Benefits', 'Front End'),
('PR-177', 'Patient has not met required eligibility requirements', 'Coverage / Benefits', 'Front End'),
('PR-31', 'Patient cannot be identified as our insured', 'Coverage / Benefits', 'Front End'),
('45', 'Charge exceeds fee schedule/maximum allowable', 'Coverage / Benefits', 'Front End'),
('PR-187, OA-23', 'Consumer spending account payment adjustment + Impact of prior payer adjudication including payments/adjustments.', 'Coverage / Benefits', 'Front End'),
('PR-45', 'Charge exceeds fee schedule/maximum allowable', 'Coverage / Benefits', 'Front End'),
('PR-27', 'Expenses incurred after coverage terminated', 'Coverage / Benefits', 'Front End'),
('PR-32', 'Our records indicate dependent not covered', 'Coverage / Benefits', 'Front End'),
('PI-22', 'This care may be covered by another payer per COB.', 'Coordination of Benefits', 'Front End'),
('CO-177', 'Patient has not met required eligibility requirements', 'Coverage / Benefits', 'Front End'),
('PR-187', 'Consumer spending account payment adjustment', 'Coverage / Benefits', 'Front End'),
('N448', 'This drug/service/supply is not included in the fee schedule or contracted/legislated fee arrangement.', 'Credentialing', 'Front End'),
('N836', 'Provider W9 or Payee Registration not on file.', 'Credentialing', 'Front End'),
('MA36', 'Missing/incomplete/invalid patient name.', 'Demographic Discrepancy', 'Front End'),
('18', 'Exact duplicate claim/service (Use only with Group Code OA except where state workers'' compensation regulations requires CO).', 'Duplicate', 'Middle'),
('N522', 'Duplicate of a claim processed, or to be processed, as a crossover claim.', 'Duplicate', 'Middle'),
('PR-50', 'These are non-covered services because not deemed medically necessary', 'Medical Necessity', 'Back End'),
('CO-50', 'These are non-covered services because not deemed medically necessary', 'Medical Necessity', 'Back End'),
('OA-50', 'These are non-covered services because not deemed medically necessary', 'Medical Necessity', 'Back End'),
('148', 'Claim/service rejected at this time because information from another provider was not provided or was insufficient/incomplete.', 'Medical Records', 'Back End'),
('150', 'Payment adjusted because the payer deems the information submitted does not support this level of service.', 'Medical Records', 'Back End'),
('163', 'Attachment/other documentation referenced on the claim was not received.', 'Medical Records', 'Back End'),
('226', 'Information requested from the Billing/Rendering Provider was not provided or not provided timely or was insufficient/incomplete.', 'Medical Records', 'Back End'),
('251', 'The attachment/other documentation that was received was incomplete or deficient.', 'Medical Records', 'Back End'),
('252', 'An attachment/other documentation is required to adjudicate this claim/service.', 'Medical Records', 'Back End'),
('B12', 'Services not documented in patient''s medical records.', 'Medical Records', 'Back End'),
('M127', 'Missing patient medical record for this service.', 'Medical Records', 'Back End'),
('M135', 'Missing/incomplete/invalid plan of treatment.', 'Medical Records', 'Back End'),
('M29', 'Missing operative report.', 'Medical Records', 'Back End'),
('M30', 'Missing pathology report.', 'Medical Records', 'Back End'),
('M31', 'Missing radiology report.', 'Medical Records', 'Back End'),
('M60', 'Missing Certificate of Medical Necessity.', 'Medical Records', 'Back End'),
('MA113', 'Incomplete/invalid taxpayer identification number (TIN) submitted by you per the Internal Revenue Service.', 'Medical Records', 'Back End'),
('MA120', 'Missing/incomplete/invalid CLIA certification number.', 'Medical Records', 'Back End'),
('N163', 'Medical record does not support code billed per the code definition.', 'Medical Records', 'Back End'),
('N206', 'The supporting documentation does not match the information sent on the claim.', 'Medical Records', 'Back End'),
('N221', 'Missing Admitting History and Physical report.', 'Medical Records', 'Back End'),
('N237', 'Incomplete/invalid patient medical record for this service.', 'Medical Records', 'Back End'),
('N3', 'Missing consent form.', 'Medical Records', 'Back End'),
('N366', 'Requested information not provided.', 'Medical Records', 'Back End'),
('N394', 'Incomplete/invalid progress notes or report.', 'Medical Records', 'Back End'),
('N395', 'Missing laboratory report.', 'Medical Records', 'Back End'),
('N455', 'Missing Physician Order.', 'Medical Records', 'Back End'),
('N456', 'Incomplete/invalid Physician Order.', 'Medical Records', 'Back End'),
('N459', 'Missing Discharge Summary.', 'Medical Records', 'Back End'),
('N463', 'Missing support data for claim.', 'Medical Records', 'Back End'),
('N467', 'Missing Report of Tests and Analysis Report.', 'Medical Records', 'Back End'),
('N489', 'Missing referral form.', 'Medical Records', 'Back End'),
('N50', 'Missing/incomplete/invalid discharge information.', 'Medical Records', 'Back End'),
('N661', 'Documentation does not support that the services rendered were medically necessary.', 'Medical Records', 'Back End'),
('N683', 'Missing/Incomplete/Invalid prior treatment documentation.', 'Medical Records', 'Back End'),
('N686', 'Missing/incomplete/Invalid questionnaire needed to complete payment determination.', 'Medical Records', 'Back End'),
('N705', 'Incomplete/invalid documentation.', 'Medical Records', 'Back End'),
('N706', 'Missing documentation.', 'Medical Records', 'Back End'),
('N707', 'Incomplete/invalid orders.', 'Medical Records', 'Back End'),
('N710', 'Missing notes.', 'Medical Records', 'Back End'),
('N888', 'Alert: An electronic request for additional information has been sent for this claim.', 'Medical Records', 'Back End'),
('PI-252', 'Attachment/documentation required to adjudicate', 'Medical Records', 'Back End'),
('PR-226', 'Information requested from provider was not provided or insufficient', 'Medical Records', 'Back End'),
('PR-227', 'Information requested from patient/member was not provided or insufficient', 'Medical Records', 'Back End'),
('PI-B12', 'Services not documented', 'Medical Records', 'Back End'),
('PI-226', 'Information requested from provider was not provided or insufficient', 'Medical Records', 'Back End'),
('CO-252', 'Attachment/documentation required to adjudicate', 'Medical Records', 'Back End'),
('CO-226', 'Information requested from provider was not provided or insufficient', 'Medical Records', 'Back End'),
('PR-252', 'Attachment/documentation required to adjudicate', 'Medical Records', 'Back End'),
('PI-252, CO-45', 'Attachment/documentation required to adjudicate + Charge exceeds fee schedule/maximum allowable', 'Medical Records', 'Back End'),
('CO-B12', 'Services not documented', 'Medical Records', 'Back End'),
('PI-251', 'Attachment/documentation received not sufficient', 'Medical Records', 'Back End'),
('PI-252, PI-252', 'Attachment/documentation required to adjudicate + Attachment/documentation required to adjudicate', 'Medical Records', 'Back End'),
('PR-2', 'Coinsurance amount', 'Not Denied', 'Not Applicable'),
('PR-1', 'Deductible amount', 'Not Denied', 'Not Applicable'),
('CO-45', 'Charge exceeds fee schedule/maximum allowable', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2', 'Deductible amount + Coinsurance amount', 'Not Denied', 'Not Applicable'),
('2', 'Coinsurance amount', 'Not Denied', 'Not Applicable'),
('PR-3', 'Co-payment amount', 'Not Denied', 'Not Applicable'),
('1', 'Deductible amount', 'Not Denied', 'Not Applicable'),
('CO-147', 'Provider contracted/negotiated discount', 'Not Denied', 'Not Applicable'),
('1, 2', 'Deductible amount + Coinsurance amount', 'Not Denied', 'Not Applicable'),
('PR-2, PR-3', 'Coinsurance amount + Co-payment amount', 'Not Denied', 'Not Applicable'),
('PR-1, PR-96', 'Deductible amount + Non-covered charge(s)', 'Not Denied', 'Not Applicable'),
('PR-2, CO-45', 'Coinsurance amount + Charge exceeds fee schedule/maximum allowable', 'Not Denied', 'Not Applicable'),
('PR-A1', 'Claim denied charges are patient responsibility per liability', 'Not Denied', 'Not Applicable'),
('PR-1, PR-3', 'Deductible amount + Co-payment amount', 'Not Denied', 'Not Applicable'),
('3', 'Co-payment amount', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2, PR-3', 'Deductible amount + Coinsurance amount + Co-payment amount', 'Not Denied', 'Not Applicable'),
('PR-100, PR-2', 'Payment made to patient/insured + Coinsurance amount', 'Not Denied', 'Not Applicable'),
('2, 3', 'Coinsurance amount + Co-payment amount', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2, CO-45', 'Deductible amount + Coinsurance amount + Charge exceeds fee schedule/maximum allowable', 'Not Denied', 'Not Applicable'),
('CO-45, PR-A1', 'Charge exceeds fee schedule/maximum allowable + Claim denied charges are patient responsibility per liability', 'Not Denied', 'Not Applicable'),
('CO-A1', 'Claim denied charges are patient responsibility per liability', 'Not Denied', 'Not Applicable'),
('PR-2, PR-45', 'Coinsurance amount + Charge exceeds fee schedule/maximum allowable', 'Not Denied', 'Not Applicable'),
('PR-2, OA-94', 'Coinsurance amount + Processed in excess of charges', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2, OA-94', 'Deductible amount + Coinsurance amount + Processed in excess of charges', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2, PR-96', 'Deductible amount + Coinsurance amount + Non-covered charge(s)', 'Not Denied', 'Not Applicable'),
('PR-1, PR-2, PR-242', 'Deductible amount + Coinsurance amount + Services not provided by network/primary care providers', 'Not Denied', 'Not Applicable'),
('OA-187', 'Consumer spending account payment adjustment', 'Not Denied', 'Not Applicable'),
('PR-100', 'Payment made to patient/insured', 'Not Denied', 'Not Applicable'),
('PR-1, CO-45', 'Deductible amount + Charge exceeds fee schedule/maximum allowable', 'Not Denied', 'Not Applicable'),
('CO-B11', 'Transferred to proper payer for processing', 'Not Denied', 'Not Applicable'),
('OA-A1', 'Claim denied charges are patient responsibility per liability', 'Not Denied', 'Not Applicable'),
('PR-1, PR-242', 'Deductible amount + Services not provided by network/primary care providers', 'Not Denied', 'Not Applicable'),
('PR-2, PR-242', 'Coinsurance amount + Services not provided by network/primary care providers', 'Not Denied', 'Not Applicable'),
('CO-193', 'Original payment decision is being maintained', 'Other', 'Back End'),
('OA-133', 'The disposition of the claim/service is pending further review.', 'Other', 'Back End'),
('PI-193', 'Original payment decision is being maintained', 'Other', 'Back End'),
('PR-39', 'Services denied at patient''s request', 'Other', 'Front End'),
('227', 'Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete.', 'Patient Contact', 'Back End'),
('N179', 'Additional information has been requested from the member.', 'Patient Contact', 'Back End'),
('26', 'Expenses incurred prior to coverage.', 'Policy Termination', 'Front End'),
('27', 'Expenses incurred after coverage terminated.', 'Policy Termination', 'Front End'),
('200', 'Expenses incurred during lapse in coverage.', 'Policy Termination', 'Front End'),
('DE8', 'The patient was not eligible for coverage on this date of service. Under our guidelines, claims are only considered for patients who are eligible on the date of service.  As a result, the claim is denied.', 'Policy Termination', 'Front End'),
('N52', 'Patient not enrolled in the billing provider''s managed care plan on the date of service.', 'Policy Termination', 'Front End'),
('N619', 'Coverage terminated for non-payment of premium.', 'Policy Termination', 'Front End'),
('N650', 'This policy was not in effect for this date of loss.', 'Policy Termination', 'Front End'),
('29', 'The time limit for filing has expired.', 'Timely Filing Limit', 'Back End'),
('164', 'Claim/Service adjusted because the attachment referenced on the claim was not received in a timely fashion.', 'Timely Filing Limit', 'Back End'),
('286', 'Appeal time limits not met.', 'Timely Filing Limit', 'Back End'),
('N102', 'This claim has been denied without reviewing the medical record because the requested records were not received or were not received timely.', 'Timely Filing Limit', 'Back End'),
('PR-29', 'Time limit for filing expired', 'Timely Filing Limit', 'Back End'),
('PI-29', 'Time limit for filing expired', 'Timely Filing Limit', 'Back End'),
('CO-29', 'Time limit for filing expired', 'Timely Filing Limit', 'Back End'),
('OA-29', 'Time limit for filing expired', 'Timely Filing Limit', 'Back End'),
('PR-286', 'Appeal time limits not met', 'Timely Filing Limit', 'Back End')
ON CONFLICT (remittance_code) DO UPDATE SET
  remittance_description = EXCLUDED.remittance_description,
  group = EXCLUDED.group,
  rcm_section = EXCLUDED.rcm_section;
