-- ar_aging
CREATE TABLE ar_aging (
    customer_account VARCHAR(20),
    charge_id VARCHAR(20) PRIMARY KEY,
    claim_id VARCHAR(20),
    claim_first_billed_date VARCHAR(20),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    charge_entered_date VARCHAR(20),
    charge_primary_payer_name TEXT,
    charge_primary_payer_id VARCHAR(50),
    practice_name TEXT,
    office_name TEXT,
    charge_current_payer_name TEXT,
    facility_name TEXT,
    claim_patient_id VARCHAR(50),
    charge_cpt_code VARCHAR(20),
    charge_cpt_description VARCHAR(100),
    revenue_code VARCHAR(20),
    patient_full_name TEXT,
    charge_fromdate_age TEXT,
    charge_fromdate_age_days VARCHAR(255),
    charge_first_bill_date_age VARCHAR(100),
    charge_first_bill_date_age_days VARCHAR(255),
    charge_balance VARCHAR(50),
    charge_balance_due_ins VARCHAR(255),
    charge_balance_due_other VARCHAR(50),
    charge_balance_due_pat VARCHAR(50),
    charge_balance_at_collections VARCHAR(50),
    charge_insurance_payments VARCHAR(50),
    charge_patient_payments VARCHAR(50),
    charge_total_payments VARCHAR(50),
    patient_stmts_sent_electronically VARCHAR(50),
    patient_statements_printed VARCHAR(50)
);

-- charges_on_hold
CREATE TABLE charges_on_hold (
    customer_account VARCHAR(20),
    practice_name_id VARCHAR(100),
    practice_name VARCHAR(100),
    facility_name VARCHAR(100),
    office_name VARCHAR(100),
    charge_primary_payer_name VARCHAR(100),
    charge_patient_id VARCHAR(50),
    charge_id VARCHAR(50),
    charge_claim_id VARCHAR(50),
    charge_debit_id VARCHAR(50),
    charge_claim_id_dup VARCHAR(50),
    charge_patient_id_dup VARCHAR(50),
    patient_full_name VARCHAR(100),
    charge_entered_date VARCHAR(20),
    charge_entered_age VARCHAR(50),
    charge_cpt_code VARCHAR(50),
    charge_rev_code VARCHAR(50),
    type_of_bill VARCHAR(50),
    charge_entered_age_days VARCHAR(10),
    charge_from_date VARCHAR(20),
    times_billed VARCHAR(10),
    charge_to_date VARCHAR(20),
    charge_amount VARCHAR(50),
    payer_type VARCHAR(50),
    claim_status VARCHAR(50),
    claim_set_to_status VARCHAR(50)
);


-- claim_stage_breakdown
CREATE TABLE claim_stage_breakdown (
    customer_account VARCHAR(20),
    practice_name VARCHAR(100),
    claim_id VARCHAR(50),
    charge_id VARCHAR(50),
    patient_id VARCHAR(50),
    patient_full_name VARCHAR(100),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    charge_entered_date VARCHAR(20),
    type_of_bill VARCHAR(50),
    charge_cpt_code VARCHAR(50),
    charge_rev_code VARCHAR(50),
    charge_amount VARCHAR(50),
    charge_primary_payer_name VARCHAR(100),
    charge_current_payer_name VARCHAR(100),
    claim_status TEXT,
    charge_balance VARCHAR(50),
    charge_balance_due_ins VARCHAR(50),
    charge_balance_due_other VARCHAR(50),
    charge_balance_due_pat VARCHAR(50),
    charge_balance_at_collections VARCHAR(50)
);

-- denial_trends
CREATE TABLE denial_trends (
    customer_account VARCHAR(20),
    facility_name VARCHAR(100),
    practice_name VARCHAR(100),
    charge_entered_date VARCHAR(20),
    office_name VARCHAR(100),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    charge_first_bill_date VARCHAR(20),
    patient_id VARCHAR(50),
    patient_full_name VARCHAR(100),
    charge_id VARCHAR(50),
    charge_rev_code VARCHAR(50),
    charge_cpt_code VARCHAR(50),
    remark_codes TEXT,
    unpaid_reason_codes TEXT,
    charge_primary_payment_date VARCHAR(20),
    payment_received VARCHAR(20),
    payment_entered VARCHAR(20),
    charge_primary_payer_name VARCHAR(100),
    payer_name VARCHAR(100),
    charge_amount VARCHAR(50),
    insurance_paid_amount VARCHAR(50)
);

-- gross_billing
CREATE TABLE gross_billing (
    customer_account VARCHAR(20),
    office_name VARCHAR(100),
    facility_name VARCHAR(100),
    practice_name VARCHAR(100),
    charge_primary_payer_name VARCHAR(100),
    charge_patient_id VARCHAR(50),
    charge_id VARCHAR(50),
    charge_claim_id VARCHAR(50),
    patient_full_name VARCHAR(100),
    primary_payer_member_id VARCHAR(50),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    charge_entered_date VARCHAR(20),
    type_of_bill VARCHAR(50),
    claim_first_billed_date VARCHAR(20),
    charge_cpt_code VARCHAR(50),
    charge_units_sum VARCHAR(10),
    charge_amount VARCHAR(50),
    charge_rev_code VARCHAR(50),
    charge_primary_payer_name_dup VARCHAR(100),
    charge_current_payer_name VARCHAR(100),
    claim_status TEXT
);

-- payment_trend
CREATE TABLE payment_trend (
    customer_account VARCHAR(20),
    facility_name VARCHAR(100),
    office_name VARCHAR(100),
    practice_name VARCHAR(100),
    charge_entered_date VARCHAR(20),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    patient_full_name VARCHAR(100),
    payment_source VARCHAR(50),
    payment_allowed_amount VARCHAR(50),
    charge_patient_id VARCHAR(50),
    charge_id VARCHAR(50),
    charge_rev_code VARCHAR(20),
    charge_cpt_code VARCHAR(20),
    type_of_bill VARCHAR(50),
    charge_claim_id VARCHAR(50),
    payer_name VARCHAR(100),
    primary_payer_member_id VARCHAR(50),
    charge_amount VARCHAR(50),
    insurance_paid_amount VARCHAR(50),
    payment_total_paid VARCHAR(50),
    payment_total_applied VARCHAR(50),
    charge_insurance_adjustments VARCHAR(50),
    charge_patient_adjustments VARCHAR(50),
    charge_total_adjustments VARCHAR(50),
    payment_received VARCHAR(20),
    payment_entered VARCHAR(20),
    insurance_applied_amount VARCHAR(50),
    patient_applied_amount VARCHAR(50),
    payment_applied_amount VARCHAR(50),
    payment_unapplied_amount VARCHAR(50)
);

-- quadrant_performance
CREATE TABLE quadrant_performance (
    customer_account VARCHAR(20),
    facility_name VARCHAR(100),
    office_name VARCHAR(100),
    practice_name VARCHAR(100),
    charge_entered_date VARCHAR(20),
    charge_from_date VARCHAR(20),
    charge_to_date VARCHAR(20),
    patient_full_name VARCHAR(100),
    payment_source VARCHAR(50),
    payment_allowed_amount VARCHAR(50),
    charge_patient_id VARCHAR(50),
    charge_id VARCHAR(50),
    charge_rev_code VARCHAR(20),
    charge_cpt_code VARCHAR(20),
    type_of_bill VARCHAR(50),
    charge_claim_id VARCHAR(50),
    payer_name VARCHAR(100),
    primary_payer_member_id VARCHAR(50),
    charge_amount VARCHAR(50),
    insurance_paid_amount VARCHAR(50),
    payment_total_paid VARCHAR(50),
    payment_total_applied VARCHAR(50),
    charge_insurance_adjustments VARCHAR(50),
    charge_patient_adjustments VARCHAR(50),
    charge_total_adjustments VARCHAR(50),
    payment_received VARCHAR(20),
    payment_entered VARCHAR(20),
    insurance_applied_amount VARCHAR(50),
    patient_applied_amount VARCHAR(50),
    payment_applied_amount VARCHAR(50),
    payment_unapplied_amount VARCHAR(50),
    primary_ins_zip VARCHAR(50),
    primary_ins_city VARCHAR(100),
    primary_ins_state VARCHAR(50),
    primary_ins_addr_1 VARCHAR(200),
    patient_zip VARCHAR(50),
    patient_city VARCHAR(100),
    patient_state VARCHAR(50),
    patient_address_1 VARCHAR(200)
);

-- rcm_productivity
CREATE TABLE rcm_productivity (
    customer_account VARCHAR(20),
    created_by_user VARCHAR(100),
    note_count_cntunq VARCHAR(50),
    claim_id VARCHAR(50),
    last_note_date_max VARCHAR(20),
    claim_from_date VARCHAR(20),
    claim_last_billed_date VARCHAR(20),
    claim_status VARCHAR(100)
);
